### ISSUE TITLE
我在VivoX5（5.0）m上运行出现崩溃，华为mate7（Android系统6.0），三星9000（4.4）都可以

### ISSUE THREAD

**Issue by 354420603** [hss01248/SafeMediaPlayer#1]

**Comment by hss01248** [comment]
有日志? @354420603

**Comment by 354420603** [comment]
java.io.IOException: setDataSourceFD failed.: status=0x80000000
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer._setDataSource(Native Method)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1115)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1100)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1079)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1028)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:976)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:957)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at com.hss01248.mediaplayer.AudioPlayerManager.start(AudioPlayerManager.java:219)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at com.hss01248.mediaplayer.AudioPlayerManager.start(AudioPlayerManager.java:133)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at rbq.mycodedemo.MainActivity.onCreate(MainActivity.java:237)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.Activity.performCreate(Activity.java:6024)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2426)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:155)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5318)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
05-17 15:21:52.755 2699-2699/rbq.mycodedemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by 354420603** [comment]
java.io.IOException: setDataSourceFD failed.: status=0x80000000

**Comment by 354420603** [comment]
报错是这个

**Comment by hss01248** [comment]
果然是这个鬼,国产rom对原生api各种改,有的能直接new 一个mediaplayer,有的必须要用MediaPlayer.create(),有的setdatasource要用特定的那个方法,我先看看

**Comment by hss01248** [comment]
player.setDataSource(context,source);  这行报错.你不要传Uri,传string进来试一下
